site_name: Qblog
site_url: ""
use_directory_urls: False




theme:
        logo: assets/icon3.svg
        favicon: assets/icon3.svg
        name: material
        palette:
                primary: black

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences        

nav:
    - Home: index.md
